/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inventarisasset;

import connectData.*;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author User
 */
public class AssetFrame extends javax.swing.JFrame {
    private koneksi obj;
    public DefaultTableModel master_asset;
    

    /**
     * Creates new form AssetFrame
     */
    public AssetFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        obj = new koneksi();
        master_asset = new DefaultTableModel();
        TableAsset.setModel(master_asset);
        master_asset.addColumn("ID Asset");
        master_asset.addColumn("Nama Asset");
        master_asset.addColumn("Tanggal Pembelian");
        master_asset.addColumn("Biaya Pembelian");
        master_asset.addColumn("Nilai Sekarang");
       
        tampilDataAsset();
    }
    
    public void tampilDataAsset() {
    try {
            master_asset.setRowCount(0);

            String query = "SELECT * FROM master_asset";
            try (PreparedStatement preparedStatement = obj.konek.prepareStatement(query);
                 ResultSet data = preparedStatement.executeQuery()) {
                while (data.next()) {
                    Object[] line = new Object[5];
                    line[0] = data.getString("asset_id");
                    line[1] = data.getString("asset_name");
                    line[2] = data.getString("purchase_date");
                    line[3] = data.getString("purchase_cost");
                    line[4] = data.getString("current_value");
                    master_asset.addRow(line);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtIDasset = new javax.swing.JTextField();
        txtNamaAsset = new javax.swing.JTextField();
        txtTGLpembelian = new javax.swing.JTextField();
        txtBiayaPembelian = new javax.swing.JTextField();
        txtNilaiSkrng = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnCetak = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableAsset = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID Asset");

        jLabel2.setText("Nama Asset");

        jLabel3.setText("Tanggal Pembelian");

        jLabel4.setText("Biaya Pembelian");

        jLabel5.setText("Nilai Sekarang");

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnCetak.setText("Cetak");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });

        TableAsset.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableAsset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableAssetMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableAsset);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBiayaPembelian, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNamaAsset, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIDasset, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTGLpembelian, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNilaiSkrng, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSimpan)
                            .addComponent(btnEdit))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCetak)
                            .addComponent(btnHapus))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtIDasset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNamaAsset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtTGLpembelian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtBiayaPembelian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtNilaiSkrng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSimpan)
                            .addComponent(btnHapus)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit)
                    .addComponent(btnCetak))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        try {
           if (txtIDasset.getText().isEmpty()) {
               JOptionPane.showMessageDialog(this, "ID Asset belum diisi");
               txtIDasset.requestFocus();
           } else if (txtNamaAsset.getText().isEmpty()) {
               JOptionPane.showMessageDialog(this, "Nama Asset belum diisi");
               txtNamaAsset.requestFocus();
           } else if (txtTGLpembelian.getText().isEmpty()) {
               JOptionPane.showMessageDialog(this, "Tanggal Pembelian belum diisi");
               txtTGLpembelian.requestFocus(); 
           } else if (txtBiayaPembelian.getText().isEmpty()) {
               JOptionPane.showMessageDialog(this, "Biaya Pembelian belum diisi");
               txtBiayaPembelian.requestFocus();
           } else if (txtNilaiSkrng.getText().isEmpty()) {
               JOptionPane.showMessageDialog(this, "Nilai Sekarang belum diisi");
               txtNilaiSkrng.requestFocus();
           } else {
               String sql = "insert into master_asset value('"+txtIDasset.getText()+"','"+txtNamaAsset.getText()+"','"+txtTGLpembelian.getText()+"','"+txtBiayaPembelian.getText()+"','"+txtNilaiSkrng.getText()+"')";;
               obj.konek.createStatement().execute(sql);
               JOptionPane.showMessageDialog(this, "data berhasil disimpan");
           }
           tampilDataAsset();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.toString());
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
         try {
        if (txtIDasset.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Pilih data yang akan dihapus");
        } else {
            String idAsset = txtIDasset.getText();
            String sql = "DELETE FROM master_asset WHERE asset_id = '" + idAsset + "'";
            int result = obj.konek.createStatement().executeUpdate(sql);

            if (result > 0) {
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus");
                // Kosongkan field setelah penghapusan
                txtIDasset.setText("");
                txtNamaAsset.setText("");
                txtTGLpembelian.setText("");
                txtBiayaPembelian.setText("");
                txtNilaiSkrng.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "Gagal menghapus data");
            }
            tampilDataAsset();
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.toString());
    }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void TableAssetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableAssetMouseClicked
        int baris = TableAsset.getSelectedRow();
        String asset_id = TableAsset.getValueAt(baris, 0).toString();
        String asset_name = TableAsset.getValueAt(baris, 1).toString();
        String purchase_date = TableAsset.getValueAt(baris, 2).toString();
        String purchase_cost = TableAsset.getValueAt(baris, 3).toString();
        String current_value = TableAsset.getValueAt(baris, 4).toString();
        txtIDasset.setText(asset_id);
        txtNamaAsset.setText(asset_name);
        txtTGLpembelian.setText(purchase_date);
        txtBiayaPembelian.setText(purchase_cost);
        txtNilaiSkrng.setText(current_value);
    
    }//GEN-LAST:event_TableAssetMouseClicked

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        try {
        if (txtIDasset.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Pilih data yang akan diubah");
        } else {
            String idAsset = txtIDasset.getText();
            String namaAsset = txtNamaAsset.getText();
            String tglPembelian = txtTGLpembelian.getText();
            String biayaPembelian = txtBiayaPembelian.getText();
            String nilaiSkrng = txtNilaiSkrng.getText();

            String sql = "UPDATE master_asset SET asset_name='" + namaAsset + "', purchase_date='" + tglPembelian + "', purchase_cost='" + biayaPembelian + "', current_value='" + nilaiSkrng + "' WHERE asset_id='" + idAsset + "'";
            int result = obj.konek.createStatement().executeUpdate(sql);

            if (result > 0) {
                JOptionPane.showMessageDialog(this, "Data berhasil diubah");
                // Kosongkan field setelah pengeditan
                txtIDasset.setText("");
                txtNamaAsset.setText("");
                txtTGLpembelian.setText("");
                txtBiayaPembelian.setText("");
                txtNilaiSkrng.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "Gagal mengubah data");
            }
            tampilDataAsset();
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.toString());
    }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        String path = ".\\src\\report\\reportAsset.jasper";
        try {
        // Mengatur koneksi database (gantilah parameter koneksi dengan yang sesuai)
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventaris_aset", "root", "");

        // Mengisi laporan dengan data dari database
        JasperPrint jprint = JasperFillManager.fillReport(path, null, conn);

        // Menampilkan laporan menggunakan JasperViewer
        JasperViewer jviewer = new JasperViewer(jprint, false);
        jviewer.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        jviewer.setVisible(true);

        // Menutup koneksi database setelah selesai
        conn.close();
     } catch (JRException | SQLException e) {
        // Menangkap dan menampilkan exception
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
     }
    }//GEN-LAST:event_btnCetakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AssetFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AssetFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AssetFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AssetFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AssetFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableAsset;
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtBiayaPembelian;
    private javax.swing.JTextField txtIDasset;
    private javax.swing.JTextField txtNamaAsset;
    private javax.swing.JTextField txtNilaiSkrng;
    private javax.swing.JTextField txtTGLpembelian;
    // End of variables declaration//GEN-END:variables
}
