/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inventarisasset;

import connectData.*;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author User
 */
public class transaksiAsset extends javax.swing.JFrame {
    private koneksi obj;
    public DefaultTableModel asset_transaction;
    

    /**
     * Creates new form transaksiAsset
     */
    public transaksiAsset() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        obj = new koneksi();
        asset_transaction = new DefaultTableModel();
        TableTransaksi.setModel(asset_transaction);
        asset_transaction.addColumn("ID Transaksi");
        asset_transaction.addColumn("ID Asset");
        asset_transaction.addColumn("Tipe Transaksi");
        asset_transaction.addColumn("Tanggal Transaksi");
        asset_transaction.addColumn("Jumlah Transaksi");
       
        tampilDataTransaksi();
    }
    
     public void tampilDataTransaksi() {
    try {
            asset_transaction.setRowCount(0);

            String query = "SELECT * FROM asset_transaction";
            try (PreparedStatement preparedStatement = obj.konek.prepareStatement(query);
                 ResultSet data = preparedStatement.executeQuery()) {
                while (data.next()) {
                    Object[] line = new Object[5];
                    line[0] = data.getString("transaction_id");
                    line[1] = data.getString("asset_id");
                    line[2] = data.getString("transaction_type");
                    line[3] = data.getString("transaction_date");
                    line[4] = data.getString("transaction_amount");
                    asset_transaction.addRow(line);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtIDtrans = new javax.swing.JTextField();
        txtIDasset = new javax.swing.JTextField();
        txtTipeTrans = new javax.swing.JTextField();
        txtTGLtrans = new javax.swing.JTextField();
        txtJMLHtrans = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableTransaksi = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID Transaksi");

        jLabel2.setText("ID Asset");

        jLabel3.setText("Tipe Transaksi");

        jLabel4.setText("Tanggal Transaksi");

        jLabel5.setText("Jumlah Transaksi");

        jButton1.setText("Simpan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Hapus");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Edit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Cetak");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        TableTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableTransaksiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableTransaksi);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIDtrans)
                            .addComponent(txtIDasset)
                            .addComponent(txtTipeTrans)
                            .addComponent(txtTGLtrans)
                            .addComponent(txtJMLHtrans, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtIDtrans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtIDasset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtTipeTrans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtTGLtrans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtJMLHtrans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TableTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableTransaksiMouseClicked
        int baris = TableTransaksi.getSelectedRow();
        String transaction_id = TableTransaksi.getValueAt(baris, 0).toString();
        String asset_id = TableTransaksi.getValueAt(baris, 1).toString();
        String transaction_type = TableTransaksi.getValueAt(baris, 2).toString();
        String transaction_date = TableTransaksi.getValueAt(baris, 3).toString();
        String transaction_amount = TableTransaksi.getValueAt(baris, 4).toString();
        txtIDtrans.setText(transaction_id);
        txtIDasset.setText(asset_id);
        txtTipeTrans.setText(transaction_type);
        txtTGLtrans.setText(transaction_date);
        txtJMLHtrans.setText(transaction_amount);
    }//GEN-LAST:event_TableTransaksiMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
        if (txtIDtrans.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "ID Transaksi belum diisi");
            txtIDtrans.requestFocus();
        } else if (txtIDasset.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "ID Asset belum diisi");
            txtIDasset.requestFocus();
        } else if (txtTipeTrans.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tipe Transaksi belum diisi");
            txtTipeTrans.requestFocus();
        } else if (txtTGLtrans.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tanggal Transaksi belum diisi");
            txtTGLtrans.requestFocus();
        } else if (txtJMLHtrans.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Jumlah Transaksi belum diisi");
            txtJMLHtrans.requestFocus();
        } else {
            String sql = "INSERT INTO asset_transaction VALUES (?, ?, ?, ?, ?)";
            try (PreparedStatement preparedStatement = obj.konek.prepareStatement(sql)) {
                preparedStatement.setString(1, txtIDtrans.getText());
                preparedStatement.setString(2, txtIDasset.getText());
                preparedStatement.setString(3, txtTipeTrans.getText());
                preparedStatement.setString(4, txtTGLtrans.getText());
                preparedStatement.setString(5, txtJMLHtrans.getText());
                preparedStatement.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data berhasil disimpan");
                // Kosongkan field setelah penyimpanan
                txtIDtrans.setText("");
                txtIDasset.setText("");
                txtTipeTrans.setText("");
                txtTGLtrans.setText("");
                txtJMLHtrans.setText("");
            }
        }
        tampilDataTransaksi();
    } catch (SQLException | HeadlessException e) {
        JOptionPane.showMessageDialog(this, e.toString());
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
        if (txtIDtrans.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Pilih data yang akan dihapus");
        } else {
            String idTransaksi = txtIDtrans.getText();
            String sql = "DELETE FROM asset_transaction WHERE transaction_id = ?";
            
            try (PreparedStatement preparedStatement = obj.konek.prepareStatement(sql)) {
                preparedStatement.setString(1, idTransaksi);
                int result = preparedStatement.executeUpdate();

                if (result > 0) {
                    JOptionPane.showMessageDialog(this, "Data berhasil dihapus");
                    // Kosongkan field setelah penghapusan
                    txtIDtrans.setText("");
                    txtIDasset.setText("");
                    txtTipeTrans.setText("");
                    txtTGLtrans.setText("");
                    txtJMLHtrans.setText("");
                } else {
                    JOptionPane.showMessageDialog(this, "Gagal menghapus data");
                }
            }
            tampilDataTransaksi();
        }
    } catch (SQLException | HeadlessException e) {
        JOptionPane.showMessageDialog(this, e.toString());
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
        if (txtIDtrans.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Pilih data yang akan diubah");
        } else {
            String idTransaksi = txtIDtrans.getText();
            String idAsset = txtIDasset.getText();
            String tipeTransaksi = txtTipeTrans.getText();
            String tglTransaksi = txtTGLtrans.getText();
            String jumlahTransaksi = txtJMLHtrans.getText();

            String sql = "UPDATE asset_transaction SET asset_id = ?, transaction_type = ?, transaction_date = ?, transaction_amount = ? WHERE transaction_id = ?";
            
            try (PreparedStatement preparedStatement = obj.konek.prepareStatement(sql)) {
                preparedStatement.setString(1, idAsset);
                preparedStatement.setString(2, tipeTransaksi);
                preparedStatement.setString(3, tglTransaksi);
                preparedStatement.setString(4, jumlahTransaksi);
                preparedStatement.setString(5, idTransaksi);
                
                int result = preparedStatement.executeUpdate();

                if (result > 0) {
                    JOptionPane.showMessageDialog(this, "Data berhasil diubah");
                    // Kosongkan field setelah pengeditan
                    txtIDtrans.setText("");
                    txtIDasset.setText("");
                    txtTipeTrans.setText("");
                    txtTGLtrans.setText("");
                    txtJMLHtrans.setText("");
                } else {
                    JOptionPane.showMessageDialog(this, "Gagal mengubah data");
                }
            }
            tampilDataTransaksi();
        }
    } catch (SQLException | HeadlessException e) {
        JOptionPane.showMessageDialog(this, e.toString());
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String path = ".\\src\\report\\reportTransaksi.jasper";
        try {
        // Mengatur koneksi database (gantilah parameter koneksi dengan yang sesuai)
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventaris_aset", "root", "");

        // Mengisi laporan dengan data dari database
        JasperPrint jprint = JasperFillManager.fillReport(path, null, conn);

        // Menampilkan laporan menggunakan JasperViewer
        JasperViewer jviewer = new JasperViewer(jprint, false);
        jviewer.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        jviewer.setVisible(true);

        // Menutup koneksi database setelah selesai
        conn.close();
     } catch (JRException | SQLException e) {
        // Menangkap dan menampilkan exception
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
     }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transaksiAsset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transaksiAsset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transaksiAsset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transaksiAsset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transaksiAsset().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableTransaksi;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtIDasset;
    private javax.swing.JTextField txtIDtrans;
    private javax.swing.JTextField txtJMLHtrans;
    private javax.swing.JTextField txtTGLtrans;
    private javax.swing.JTextField txtTipeTrans;
    // End of variables declaration//GEN-END:variables
}
